steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build","-t","gcr.io/$PROJECT_ID/backendnotes-176","."]
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push","gcr.io/$PROJECT_ID/backendnotes-176"]
  
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "backendnotes-176",
        "--image",
        "gcr.io/$PROJECT_ID/backendnotes-176",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "services",
        "add-iam-policy-binding",
        "backendnotes-176",
        "--member=allUsers",
        "--role=roles/run.invoker",
        "--region=us-central1"
      ]

options:
  logging: CLOUD_LOGGING_ONLY